version: "3"

services:
  frontend:
    container_name: "frontend"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    networks:
      - net

networks:
  net:
    driver: bridge
