import { SPECIALIZATION_LOCALES } from "@/entities/doctor/model/doctor.constants"
import { GENDER_LOCALES, USER_GENDER } from "@/entities/user/model/user.constants"

export const clinicFields = [
  {
    name: "clinic.legalName",
    label: "Юридическое название",
    placeholder: "ООО 'Медицинская клиника'",
    id: "legalName",
    type: "text" as const,
  },
  {
    name: "clinic.brandName",
    label: "Бренд / Название клиники",
    placeholder: "Клиника 'Здоровье'",
    id: "brandName",
    type: "text" as const,
    optional: true,
  },
  {
    name: "clinic.inn",
    label: "ИНН",
    placeholder: "7701234567",
    id: "inn",
    type: "text" as const,
  },
  {
    name: "clinic.ogrn",
    label: "ОГРН",
    placeholder: "1234567890123",
    id: "ogrn",
    type: "text" as const,
  },
  {
    name: "clinic.license",
    label: "Номер лицензии",
    placeholder: "ЛО-77-01-123456",
    id: "license",
    type: "text" as const,
  },
  {
    name: "clinic.directorName",
    label: "ФИО директора",
    placeholder: "Иванов Иван Иванович",
    id: "directorName",
    type: "text" as const,
  },
  {
    name: "clinic.directorPosition",
    label: "Должность директора",
    placeholder: "Генеральный директор",
    id: "directorPosition",
    type: "text" as const,
  },
  {
    name: "clinic.legalAddress",
    label: "Юридический адрес",
    placeholder: "г. Москва, ул. Ленина, д. 1",
    id: "legalAddress",
    type: "text" as const,
  },
  {
    name: "clinic.actualAddress",
    label: "Фактический адрес",
    placeholder: "г. Москва, ул. Ленина, д. 1",
    id: "actualAddress",
    type: "text" as const,
  },
  {
    name: "clinic.city",
    label: "Город",
    placeholder: "Москва",
    id: "city",
    type: "text" as const,
    optional: true,
  },
  {
    name: "clinic.website",
    label: "Сайт",
    placeholder: "https://clinic.ru",
    id: "website",
    type: "text" as const,
    optional: true,
  },
  {
    name: "clinic.description",
    label: "Описание клиники",
    placeholder: "Расскажите о вашей клинике...",
    id: "description",
    type: "textarea" as const,
    optional: true,
  },
]

export const doctorFields = [
  {
    name: "doctor.license",
    label: "Номер лицензии",
    placeholder: "ЛО-77-01-123456",
    id: "license",
    type: "text" as const,
  },
  {
    name: "doctor.inn",
    label: "ИНН",
    placeholder: "123456789012",
    id: "inn",
    type: "text" as const,
  },
  {
    name: "doctor.experience",
    label: "Опыт работы (лет)",
    placeholder: "10",
    id: "experience",
    type: "number" as const,
  },
  {
    name: "doctor.education",
    label: "Образование",
    placeholder: "РНИМУ им. Н.И. Пирогова",
    id: "education",
    type: "text" as const,
  },
  {
    name: "doctor.workplace",
    label: "Место работы",
    placeholder: "Частная практика или доп. информация",
    id: "workplace",
    type: "text" as const,
    optional: true,
  },
  {
    name: "doctor.birthdate",
    label: "Дата рождения",
    id: "birthdate",
    type: "date" as const,
    optional: true,
  },
  {
    name: "doctor.gender",
    label: "Пол",
    id: "gender",
    type: "select" as const,
    options: [
      { value: USER_GENDER.MALE, label: GENDER_LOCALES["MALE"].ru },
      { value: USER_GENDER.FEMALE, label: GENDER_LOCALES["FEMALE"].ru },
    ],
    optional: true,
  },
  {
    name: "doctor.specializations",
    label: "Специализации",
    id: "specializations",
    type: "multi-select" as const,
    options: Object.entries(SPECIALIZATION_LOCALES).map(([key, locale]) => ({
      label: locale.ru,
      value: key,
    })),
  },
  {
    name: "doctor.bio",
    label: "О себе / Биография",
    placeholder: "Краткая информация о ваших достижениях...",
    id: "bio",
    type: "textarea" as const,
    optional: true,
  },
]

export const patientFields = [
  {
    name: "patient.birthdate",
    label: "Дата рождения",
    id: "birthdate",
    type: "date" as const,
    optional: true,
  },
  {
    name: "patient.gender",
    label: "Пол",
    id: "gender",
    type: "select" as const,
    options: [
      { value: USER_GENDER.MALE, label: GENDER_LOCALES["MALE"].ru },
      { value: USER_GENDER.FEMALE, label: GENDER_LOCALES["FEMALE"].ru },
    ],
    optional: true,
  },
  {
    name: "patient.allergies",
    label: "Аллергии",
    placeholder: "Пыльца, цитрусовые...",
    id: "allergies",
    type: "tags" as const,
    optional: true,
  },
  {
    name: "patient.bloodType",
    label: "Группа крови",
    placeholder: "A(II) Rh+",
    id: "bloodType",
    type: "text" as const,
    optional: true,
  },
  {
    name: "patient.medicalNotes",
    label: "Медицинские примечания",
    placeholder: "Важная информация для врачей...",
    id: "medicalNotes",
    type: "textarea" as const,
    optional: true,
  },
  {
    name: "patient.chronicDiseases",
    label: "Хронические заболевания",
    placeholder: "Перечислите через запятую...",
    id: "chronicDiseases",
    type: "textarea" as const,
    optional: true,
  },
]
