export default [
  {
    id: 1,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Устранение дефектов подбородка",
    costs: "12 999" + " ₽",
    status: "Активный",
    reception: "Частная практика",
  },
  {
    id: 2,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Контурная пластика подбородка",
    costs: "12 999" + " ₽",
    status: "Активный",
    reception: "На дому",
  },
  {
    id: 3,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Коррекция лопоухости",
    costs: "12 999" + " ₽",
    status: "Активный",
    reception: "Частная практика",
  },
  {
    id: 4,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Удаление атеромы",
    costs: "12 999" + " ₽",
    status: "Активный",
    reception: "Частная практика",
  },
  {
    id: 5,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Удаление атеромы",
    costs: "12 999" + " ₽",
    status: "Активный",
    reception: "Частная практика",
  },
  {
    id: 6,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Удаление атеромы",
    costs: "12 999" + " ₽",
    status: "Активный",
    reception: "Частная практика",
  },
  {
    id: 7,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Удаление атеромы",
    costs: "12 999" + " ₽",
    status: "Активный",
    reception: "Частная практика",
  },
  {
    id: 8,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Удаление атеромы",
    costs: "12 999" + " ₽",
    status: "Активный",
    reception: "Частная практика",
  },
  {
    id: 9,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Удаление атеромы",
    costs: "12 999" + " ₽",
    status: "Активный",
    reception: "Частная практика",
  },
  {
    id: 10,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Удаление атеромы",
    costs: "12 999" + " ₽",
    status: "Активный",
    reception: "Частная практика",
  },
  {
    id: 11,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Удаление атеромы",
    costs: "12 999" + " ₽",
    status: "Активный",
    reception: "Частная практика",
  },
  {
    id: 12,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Удаление атеромы",
    costs: "12 999" + " ₽",
    status: "Активный",
    reception: "Частная практика",
  },
  {
    id: 13,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Удаление атеромы",
    costs: "12 999" + " ₽",
    status: "Активный",
    reception: "Частная практика",
  },
];
