export default [
  {
    id: 1,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Устранение дефектов подбородка",
    costs: "12 999" + " ₽",
    status: "Активный",
    reception: "Частная практика",
  },
  {
    id: 2,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Контурная пластика подбородка",
    costs: "12 999" + " ₽",
    status: "Активный",
    reception: "На дому",
  },
  {
    id: 3,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Коррекция лопоухости",
    costs: "12 999" + " ₽",
    status: "Неактивный",
    reception: "Частная практика",
  },
  {
    id: 4,
    fullName: "Сергей Васильевич Васильев",
    specialists: "Хирург",
    services: "Удаление атеромы",
    costs: "12 999" + " ₽",
    status: "Неактивный",
    reception: "Частная практика",
  },
];
