import { ROUTES } from "@/shared/model/routes"
import {
  User,
  HelpCircle,
  Briefcase,
  LayoutDashboard,
  Users,
  Star,
  SettingsIcon,
  Building2,
  Calendar,
  MessageCircle,
  Heart,
  Database,
  Settings2,
  Search,
  Stethoscope,
} from "lucide-react"

export const sectionLabels: Record<string, string> = {
  main: "ГЛАВНОЕ МЕНЮ",
  other: "ДОПОЛНИТЕЛЬНО",
}

export const navigationConfig = {
  clinic: [
    {
      id: "dashboard",
      name: "Главная",
      icon: LayoutDashboard,
      url: ROUTES.MAIN,
      section: "main",
    },
    {
      id: "profile",
      name: "Профиль",
      icon: User,
      url: ROUTES.PROFILE,
      section: "main",
    },
    {
      id: "clinic_doctors",
      name: "Врачи",
      icon: Users,
      url: ROUTES.CLINIC_DOCTORS,
      section: "main",
    },
    // {
    //     id: "services",
    //     name: "Услуги",
    //     icon: Briefcase,
    //     url: "/main/services",
    //     section: "main",
    // },
    {
      id: "appointments",
      name: "Записи на приём",
      icon: Calendar,
      url: ROUTES.APPOINTMENTS,
      section: "main",
    },
    // {
    //     id: "reviews",
    //     name: "Отзывы пациентов",
    //     icon: Star,
    //     url: "/main/reviews",
    //     section: "main",
    // },
    {
      id: "settings",
      name: "Настройки",
      icon: SettingsIcon,
      url: ROUTES.SETTINGS,
      section: "other",
      items: [
        {
          id: "general_settings",
          name: "Основные настройки",
          icon: Settings2,
          url: ROUTES.GENERAL,
        },
        {
          id: "personal_data_settings",
          name: "Персональные данные",
          icon: Database,
          url: ROUTES.PERSONAL_DATA,
        },
      ],
    },
    // {
    //   id: "help",
    //   name: "Помощь",
    //   icon: HelpCircle,
    //   url: "/main/help",
    //   section: "other",
    // },
    {
      id: "support",
      name: "Поддержка",
      icon: MessageCircle,
      url: ROUTES.SUPPORT,
      section: "other",
    },
  ],
  doctor: [
    {
      id: "dashboard",
      name: "Главная",
      icon: LayoutDashboard,
      url: ROUTES.MAIN,
      section: "main",
    },
    {
      id: "profile",
      name: "Профиль",
      icon: User,
      url: ROUTES.PROFILE,
      section: "main",
    },
    {
      id: "catalog",
      name: "Каталог",
      icon: Search,
      url: ROUTES.CATALOG,
      section: "main",
    },
    {
      id: "clinic",
      name: "Клиника",
      icon: Building2,
      url: ROUTES.DOCTOR_CLINICS,
      section: "main",
    },
    // {
    //     id: "services",
    //     name: "Услуги",
    //     icon: Briefcase,
    //     url: "/main/services",
    //     section: "main",
    // },
    {
      id: "appointments",
      name: "Записи на приём",
      icon: Calendar,
      url: ROUTES.APPOINTMENTS,
      section: "main",
    },
    // {
    //     id: "reviews",
    //     name: "Отзывы пациентов",
    //     icon: Star,
    //     url: "/main/reviews",
    //     section: "main",
    // },
    {
      id: "settings",
      name: "Настройки",
      icon: SettingsIcon,
      url: ROUTES.SETTINGS,
      section: "other",
      items: [
        {
          id: "general_settings",
          name: "Основные настройки",
          icon: Settings2,
          url: ROUTES.GENERAL,
        },
        {
          id: "personal_data_settings",
          name: "Персональные данные",
          icon: Database,
          url: ROUTES.PERSONAL_DATA,
        },
      ],
    },
    // {
    //   id: "help",
    //   name: "Помощь",
    //   icon: HelpCircle,
    //   url: "/main/help",
    //   section: "other",
    // },
    {
      id: "support",
      name: "Поддержка",
      icon: MessageCircle,
      url: ROUTES.SUPPORT,
      section: "other",
    },
  ],
  patient: [
    {
      id: "dashboard",
      name: "Главная",
      icon: LayoutDashboard,
      url: ROUTES.MAIN,
      section: "main",
    },
    {
      id: "profile",
      name: "Профиль",
      icon: User,
      url: ROUTES.PROFILE,
      section: "main",
    },
    {
      id: "catalog",
      name: "Каталог",
      icon: Search,
      url: ROUTES.CATALOG,
      section: "main",
    },
    {
      id: "appointments",
      name: "Запись на приём",
      icon: Calendar,
      url: ROUTES.APPOINTMENTS,
      section: "main",
    },
    // {
    //     id: "reviews",
    //     name: "Отзывы",
    //     icon: Star,
    //     url: "/main/reviews",
    //     section: "main",
    // },
    {
      id: "settings",
      name: "Настройки",
      icon: SettingsIcon,
      url: ROUTES.SETTINGS,
      section: "other",
      items: [
        {
          id: "general_settings",
          name: "Основные настройки",
          icon: Settings2,
          url: ROUTES.GENERAL,
        },
        {
          id: "personal_data_settings",
          name: "Персональные данные",
          icon: Database,
          url: ROUTES.PERSONAL_DATA,
        },
      ],
    },
    // {
    //   id: "help",
    //   name: "Помощь",
    //   icon: HelpCircle,
    //   url: "/main/help",
    //   section: "other",
    // },
    {
      id: "support",
      name: "Поддержка",
      icon: MessageCircle,
      url: ROUTES.SUPPORT,
      section: "other",
    },
  ],
}
