export const SERVICE_CATEGORY = {
  CONSULTATION: "CONSULTATION",
  DIAGNOSTICS: "DIAGNOSTICS",
  SURGERY_FACE: "SURGERY_FACE",
  SURGERY_BODY: "SURGERY_BODY",
  SURGERY_RECONSTRUCTIVE: "SURGERY_RECONSTRUCTIVE",
  COSMETOLOGY_INJECTABLE: "COSMETOLOGY_INJECTABLE",
  COSMETOLOGY_HARDWARE: "COSMETOLOGY_HARDWARE",
  AESTHETIC_MEDICINE: "AESTHETIC_MEDICINE",
  REHABILITATION: "REHABILITATION",
  ANALYSIS: "ANALYSIS",
  OTHER: "OTHER",
} as const

export const SERVICE_CATEGORY_LOCALES = {
  [SERVICE_CATEGORY.CONSULTATION]: { ru: "Консультации" },
  [SERVICE_CATEGORY.DIAGNOSTICS]: { ru: "Диагностика" },
  [SERVICE_CATEGORY.SURGERY_FACE]: { ru: "Хирургия лица" },
  [SERVICE_CATEGORY.SURGERY_BODY]: { ru: "Хирургия тела" },
  [SERVICE_CATEGORY.SURGERY_RECONSTRUCTIVE]: { ru: "Реконструктивная хирургия" },
  [SERVICE_CATEGORY.COSMETOLOGY_INJECTABLE]: { ru: "Инъекционная косметология" },
  [SERVICE_CATEGORY.COSMETOLOGY_HARDWARE]: { ru: "Аппаратная косметология" },
  [SERVICE_CATEGORY.AESTHETIC_MEDICINE]: { ru: "Эстетическая медицина" },
  [SERVICE_CATEGORY.REHABILITATION]: { ru: "Реабилитация" },
  [SERVICE_CATEGORY.ANALYSIS]: { ru: "Анализы" },
  [SERVICE_CATEGORY.OTHER]: { ru: "Прочее" },
} as const
