import { User, HelpCircle, Briefcase, LayoutDashboard, Users, Star, SettingsIcon, Building2, Calendar, MessageCircle, Heart } from "lucide-react";

export const sectionLabels: Record<string, string> = {
    main: "ГЛАВНОЕ МЕНЮ",
    other: "ДОПОЛНИТЕЛЬНО",
};

export const navigationConfig = {
    clinic: [
        {
            id: "dashboard",
            name: "Главная",
            icon: LayoutDashboard,
            url: "/main",
            section: "main",
        },
        {
            id: "profile",
            name: "Профиль",
            icon: User,
            url: "/main/profile",
            section: "main",
        },
        {
            id: "specialists",
            name: "Специалисты",
            icon: Users,
            url: "/main/specialists",
            section: "main",
        },
        {
            id: "services",
            name: "Услуги",
            icon: Briefcase,
            url: "/main/services",
            section: "main",
        },
        {
            id: "appointments",
            name: "Записи на приём",
            icon: Calendar,
            url: "/main/appointments",
            section: "main",
        },
        {
            id: "reviews",
            name: "Отзывы пациентов",
            icon: Star,
            url: "/main/reviews",
            section: "main",
        },
        {
            id: "settings",
            name: "Настройки",
            icon: SettingsIcon,
            url: "/main/settings",
            section: "other",
        },
        {
            id: "help",
            name: "Помощь",
            icon: HelpCircle,
            url: "/main/help",
            section: "other",
        },
        {
            id: "support",
            name: "Поддержка",
            icon: MessageCircle,
            url: "/main/support",
            section: "other",
        },
    ],
    doctor: [
        {
            id: "dashboard",
            name: "Главная",
            icon: LayoutDashboard,
            url: "/main",
            section: "main",
        },
        {
            id: "profile",
            name: "Профиль",
            icon: User,
            url: "/main/profile",
            section: "main",
        },
        {
            id: "clinic",
            name: "Клиника",
            icon: Building2,
            url: "/main/clinic",
            section: "main",
        },
        {
            id: "services",
            name: "Услуги",
            icon: Briefcase,
            url: "/main/services",
            section: "main",
        },
        {
            id: "appointments",
            name: "Записи на приём",
            icon: Calendar,
            url: "/main/appointments",
            section: "main",
        },
        {
            id: "reviews",
            name: "Отзывы пациентов",
            icon: Star,
            url: "/main/reviews",
            section: "main",
        },
        {
            id: "settings",
            name: "Настройки",
            icon: SettingsIcon,
            url: "/main/settings",
            section: "other",
        },
        {
            id: "help",
            name: "Помощь",
            icon: HelpCircle,
            url: "/main/help",
            section: "other",
        },
        {
            id: "support",
            name: "Поддержка",
            icon: MessageCircle,
            url: "/main/support",
            section: "other",
        },
    ],
    patient: [
        {
            id: "dashboard",
            name: "Главная",
            icon: LayoutDashboard,
            url: "/main",
            section: "main",
        },
        {
            id: "profile",
            name: "Профиль",
            icon: User,
            url: "/main/profile",
            section: "main",
        },
        {
            id: "favorites",
            name: "Избранное",
            icon: Heart,
            url: "/main/favorites",
            section: "main",
        },
        {
            id: "appointments",
            name: "Запись на приём",
            icon: Calendar,
            url: "/main/appointments",
            section: "main",
        },
        {
            id: "reviews",
            name: "Отзывы",
            icon: Star,
            url: "/main/reviews",
            section: "main",
        },
        {
            id: "settings",
            name: "Настройки",
            icon: SettingsIcon,
            url: "/main/settings",
            section: "other",
        },
        {
            id: "help",
            name: "Помощь",
            icon: HelpCircle,
            url: "/main/help",
            section: "other",
        },
        {
            id: "support",
            name: "Поддержка",
            icon: MessageCircle,
            url: "/main/support",
            section: "other",
        },
    ],
};
